export const roomGroupData = {
  sequence: 0,
  rooms: [
    {
      sequence: 0,
      roomGroupId: "aBK180000000EArGAM",
      roomCode: null,
      name: "Room 1 API TEST",
      jobId: "a8W180000004jv2EAA",
      isShared: false,
      id: "a8Z18000000TJCqEAO"
    },
    {
      sequence: 1,
      roomGroupId: "aBK180000000EArGAM",
      roomCode: null,
      name: "Equipment Room API",
      jobId: "a8W180000004jv2EAA",
      isShared: true,
      id: "a8Z18000000TJCrEAO"
    }
  ],
  name: "Main Floor",
  jobId: "a8W180000004jv2EAA",
  id: "aBK180000000EArGAM"
};

export const panelData = {
  roomId: "a8Z18000000TJCrEAO",
  panelType: "QO",
  panelSize: 42,
  name: "Test API Panel",
  modules: [],
  jobId: "a8W180000004jv2EAA",
  id: "a8a1800000092eFAAQ",
  circuits: []
};

export const moduleData = {
  voltage: 120,
  size: 2,
  panelSlot: 1,
  panelId: "a8a1800000092eFAAQ",
  output_B_loadId: null,
  output_B_circuitId: null,
  output_B_capacity: 300,
  output_A_loadId: "a8b180000009whkAAA",
  output_A_circuitId: "aBT1800000005QzGAI",
  output_A_capacity: 300,
  name: "QO Dual Forward Phase Dimmer",
  image: null,
  id: "aBS180000000GUXGA2",
  elementType: "Module",
  dtProductId: "aBC1800000007BEGAY",
  capacityUse: 120,
  capacityTotal: 600
};

export const circuitData = {
  voltage: 120,
  size: 1,
  powerCapacity: 1440,
  panelSlot: 5,
  panelId: "a8a1800000092eFAAQ",
  name: "APICircuit",
  loads: ["a8b180000009whkAAA", "a8b180000009wm6AAA"],
  image: null,
  id: "aBT1800000005QzGAI",
  elementType: "Breaker",
  dtProductId: "aBC1800000007RpGAI",
  color: "#ff5f00",
  capacityUse: 240,
  amperage: 15
};

export const jobData = {
  roomGroups: [
    {
      sequence: 0,
      rooms: [
        {
          sequence: 0,
          roomGroupId: "aBK180000000EArGAM",
          roomCode: null,
          name: "Room 1 API TEST",
          jobId: "a8W180000004jv2EAA",
          isShared: false,
          id: "a8Z18000000TJCqEAO"
        }
      ],
      name: "Main Floor",
      jobId: "a8W180000004jv2EAA",
      id: "aBK180000000EArGAM"
    }
  ],
  panels: [],
  name: "test defaults edited 2",
  loads: [
    {
      roomId: "a8Z18000000TJCqEAO",
      panelLocationId: null,
      name: "Load 1 API",
      moduleType: null,
      moduleDisplayName: null,
      loadNumber: null,
      jobId: "a8W180000004jv2EAA",
      id: "a8b180000009wm6AAA",
      fixtureQty: 4,
      fixtureId: "a8c180000002RtlAAE",
      dtEquipmentId: null,
      connectionLV: "BLE",
      connectionHV: "Module"
    }
  ],
  keypadLocations: [
    {
      roomId: "a8Z18000000TJCqEAO",
      name: "Bar Lights",
      keypads: [],
      jobId: "a8W180000004jv2EAA",
      id: "a8d1800000014jFAAQ",
      dtProductId: "aBC18000000076lGAA"
    },
    {
      roomId: "a8Z18000000TJCqEAO",
      name: "Keypad 2 test EDITED",
      keypads: [
        {
          position: 3,
          name: "Keypad 2 test EDITED",
          loadId: null,
          keypadLocationId: "a8d1800000014jAAAQ",
          id: "a8k180000001n3FAAQ",
          engProductId: null,
          dtProductId: "aBC180000000793GAA",
          dtEquipmentId: null,
          button4text2: null,
          button4text: null,
          button3text2: null,
          button3text: null,
          button2text2: null,
          button2text: null,
          button1text2: null,
          button1text: null
        },
        {
          position: 1,
          name: "Keypad 1 test",
          loadId: null,
          keypadLocationId: "a8d1800000014jAAAQ",
          id: "a8k180000001n30AAA",
          engProductId: null,
          dtProductId: "aBC180000000793GAA",
          dtEquipmentId: "a8e180000001WY0AAM",
          button4text2: null,
          button4text: null,
          button3text2: null,
          button3text: null,
          button2text2: null,
          button2text: null,
          button1text2: null,
          button1text: null
        }
      ],
      jobId: "a8W180000004jv2EAA",
      id: "a8d1800000014jAAAQ",
      dtProductId: "aBC180000000793GAA"
    }
  ],
  jobType: null,
  jobEquipment: [],
  id: "a8W180000004jv2EAA",
  fixtures: [
    {
      wattage: 120,
      partNumber: "234",
      name: "Nermal's Fixture",
      manufacturer: "USAI",
      jobId: "a8W180000004jv2EAA",
      id: "a8c180000002S4ZAAU",
      controlTypeLV: "BLE",
      controlType: "Forward Phase"
    }
  ],
  defaultWireGauge: "14",
  defaultVoltage: "120v",
  defaultPricing: "MSRP",
  defaultPanelStyle: "QO",
  defaultPanelSize: "42",
  defaultMeasurement: "Imperial",
  defaultKeypadFamily: "Metropolitan",
  defaultKeypadColor: "Black",
  created: 1587138531000,
  accId: "0017000000Nk6YKAAZ"
};

export const roomData = {
  sequence: 0,
  roomGroupId: "aBK180000000EArGAM",
  roomCode: null,
  name: "Room 1 API TEST",
  jobId: "a8W180000004jv2EAA",
  isShared: false,
  id: "a8Z18000000TJCqEAO"
};

export const fixtureData = {
  wattage: 2,
  partNumber: "x3",
  name: "xxfixture",
  manufacturer: "x",
  jobId: "a8W180000004gwIEAQ",
  id: "a8c1800000024leAAA",
  controlTypeLV: "None",
  controlType: "Adaptive Phase"
};

export const loadData = {
  roomId: "a8Z18000000TJ7REAW",
  panelLocationId: null,
  name: "relay load",
  moduleType: null,
  moduleDisplayName: "test",
  loadNumber: "233",
  jobId: "a8W180000004gwIEAQ",
  id: "a8b180000009uULAAY",
  fixtureQty: 9,
  fixtureId: "a8c1800000024l4AAA",
  dtEquipmentId: null,
  connectionLV: null,
  connectionHV: "Module"
};

export const keypadLocationData = {
  roomId: "a8Z18000000TJ80EAG",
  name: "Keypad Location 17",
  keypads: [],
  jobId: "a8W180000004gwIEAQ",
  id: "a8d18000000141EAAQ",
  dtProductId: "aBC18000000076lGAA"
};

export const keypadData = {
  position: 1,
  name: "New Keypad",
  loadId: null,
  keypadLocationId: "a8d18000000141KAAQ",
  id: "a8k180000001mIGAAY",
  engProductId: null,
  dtProductId: "aBC180000000799GAA",
  dtEquipmentId: null,
  button4text2: null,
  button4text: null,
  button3text2: null,
  button3text: null,
  button2text2: null,
  button2text: null,
  button1text2: null,
  button1text: null
};

export const equipmentData = {
  name: "10 Keypad Power and Controller",
  maxConnections: 10,
  loads: [],
  keypads: ["a8k180000001n30AAA"],
  jobId: "a8W180000004jv2EAA",
  id: "a8e180000001WY0AAM",
  equipmentType: "Lighting",
  dtProductId: "aBC1800000007DEGAY",
  controllerType: "Keypads"
};

export const productData = {
  type: "Module",
  style: null,
  productSKU: "SPM-H2APD10-00",
  productId: "01t7000000RaYD1AAN",
  productDescription: "HOMELINE DUAL ADAPTIVE PHASE DIMMER",
  price: 150.0,
  name: "HOMELINE DUAL ADAPTIVE PHASE DIMMER",
  msrp: 300.0,
  moduleType: "Adaptive Phase",
  maxVoltage: 120,
  maxConnections: null,
  image: null,
  id: "aBC1800000007BDGAY",
  finish: null,
  family: "Homeline",
  equipmentType: null,
  diagram: null,
  controllerType: null,
  control: null,
  configuration: null,
  buttonLayout: null,
  buttonCount: null,
  amperage: 15,
  active: true
};

export const fullProductData = {
  modules: [
    {
      type: "Module",
      style: null,
      productSKU: "SPM-H2APD10-00",
      productId: "01t7000000RaYD1AAN",
      productDescription: "HOMELINE DUAL ADAPTIVE PHASE DIMMER",
      price: 150.0,
      name: "HOMELINE DUAL ADAPTIVE PHASE DIMMER",
      msrp: 300.0,
      moduleType: "Adaptive Phase",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007BDGAY",
      finish: null,
      family: "Homeline",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 15,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "SPM-Q2FPD10-00",
      productId: "01t7000000RaYDVAA3",
      productDescription: "QO DUAL FORWARD PHASE DIMMER",
      price: 125.0,
      name: "QO DUAL FORWARD PHASE DIMMER",
      msrp: 250.0,
      moduleType: "Forward Phase",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007BEGAY",
      finish: null,
      family: "QO",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 15,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "RPM-H1R40240-00",
      productId: "01t0g00000ZF2A2AAL",
      productDescription: "HOMELINE RELAY 240V 30A",
      price: 125.0,
      name: "HOMELINE RELAY 240V 30A",
      msrp: 250.0,
      moduleType: "Relay",
      maxVoltage: 240,
      maxConnections: null,
      image: null,
      id: "aBC1800000007AtGAI",
      finish: null,
      family: "Homeline",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 30,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "RPM-Q2R40240-00",
      productId: "01t0g00000ZF2AlAAL",
      productDescription: "QO RELAY  240V 30 AMP",
      price: 125.0,
      name: "QO RELAY 240V 30 AMP",
      msrp: 250.0,
      moduleType: "Relay",
      maxVoltage: 340,
      maxConnections: null,
      image: null,
      id: "aBC1800000007B8GAI",
      finish: null,
      family: "QO",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 30,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "SPM-H2FPD10-00",
      productId: "01t7000000RaYB7AAN",
      productDescription: "HOMELINE DUAL FORWARD PHASE DIMMER",
      price: 125.0,
      name: "HOMELINE DUAL FORWARD PHASE DIMMER",
      msrp: 250.0,
      moduleType: "Forward Phase",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007BIGAY",
      finish: null,
      family: "Homeline",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 15,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "RPM-Q2R20120-00",
      productId: "01t0g00000ZF2AgAAL",
      productDescription: "QO DUAL RELAY 20 AMP",
      price: 125.0,
      name: "QO DUAL RELAY 20 AMP",
      msrp: 250.0,
      moduleType: "Dual Relay",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007B3GAI",
      finish: null,
      family: "QO",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 20,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "SPM-Q2APD10-00",
      productId: "01t7000000RaYDLAA3",
      productDescription: "QO DUAL ADAPTIVE PHASE DIMMER",
      price: 150.0,
      name: "QO DUAL ADAPTIVE PHASE DIMMER",
      msrp: 300.0,
      moduleType: "Adaptive Phase",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007B4GAI",
      finish: null,
      family: "QO",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 15,
      active: true
    },
    {
      type: "Module",
      style: null,
      productSKU: "RPM-H2R20120-00",
      productId: "01t0g00000ZF2AMAA1",
      productDescription: "HOMELINE DUAL RELAY 20AMP",
      price: 125.0,
      name: "HOMELINE DUAL RELAY 20AMP",
      msrp: 250.0,
      moduleType: "Dual Relay",
      maxVoltage: 120,
      maxConnections: null,
      image: null,
      id: "aBC1800000007AyGAI",
      finish: null,
      family: "Homeline",
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: 20,
      active: true
    }
  ],
  keypads: [
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-BKLV05-00",
      productId: "01t0g00000ZFEQUAA5",
      productDescription: "ECHO LOW VOLTAGE DIAL KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo 4 Button + Dial Low Voltage Black",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-dial-4button.png",
      id: "aBC1800000007APGAY",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WIK-LAS104-01",
      productId: "01t7000000TkIAmAAN",
      productDescription: "METROPOLITAN WIRELESS KEYPAD LIGHT ALMOND",
      price: 125.0,
      name: "Metropolitan 4 Button + Dial Adaptive Light Almond",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-dial-4button.png",
      id: "aBC18000000077yGAA",
      finish: "Light Almond",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-LALV05-00",
      productId: "01t0g00000ZFERlAAP",
      productDescription: "ECHO LOW VOLTAGE DIAL KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo 4 Button + Dial Low Voltage Light Almong",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-dial-4button.png",
      id: "aBC1800000007AKGAY",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 3 Button Keypad (Skinny Top)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-3button-sbb.png",
      id: "aBC18000000078SGAQ",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnytop300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Top)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-SWA105-00",
      productId: "01t0g00000ZEtbOAAT",
      productDescription:
        "ECHO WIRELESS DIAL KEYPAD - ADAPTIVE DIMMER (SNOW WHITE)",
      price: 125.0,
      name: "Echo 4 Button + Dial Adaptive Snow White",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-dial-4button.png",
      id: "aBC1800000007A5GAI",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-BKA105-00",
      productId: "01t0g00000ZFERWAA5",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - ADAPTIVE DIMMER (BLACK)",
      price: 125.0,
      name: "Echo 4 Button + Dial Adaptive Black",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-dial-4button.png",
      id: "aBC1800000007AFGAY",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Light Almond 4 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-4button-sssb.png",
      id: "aBC18000000078cGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bfatbottom300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-LAT105-00",
      productId: "01t0g00000ZFERqAAP",
      productDescription:
        "ECHO WIRELESS DIAL KEYPAD - MLV DIMMER (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo 4 Button + Dial Forward/MLV Light Almond",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-dial-4button.png",
      id: "aBC1800000007AZGAY",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPB-BKLV02-00",
      productId: "01t0g00000ZFEQEAA5",
      productDescription: "ECHO LOW VOLTAGE PADDLE KEYPAD (BLACK)",
      price: 87.5,
      name: "Echo Paddle Low Voltage Black",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC18000000079qGAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WIS-LAS102-00",
      productId: "01t7000000Gbc45AAB",
      productDescription: "METROPOLITAN WIRELESS SWITCH LIGHT ALMOND",
      price: 70.0,
      name: "Metropolitan Paddle Switch Light Almond",
      msrp: 140.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC180000000788GAA",
      finish: "Light Almond",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WIS-BKCONV-00",
      productId: "01t7000000K5OdmAAF",
      productDescription: "METROPOLITAN WIRELESS SWITCH CONVERSION KIT BLACK",
      price: 7.5,
      name: "Metropolitan Paddle Switch Black",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC180000000789GAA",
      finish: "Black",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Black 3 Button Keypad (Skinny Top)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-3button-sbb.png",
      id: "aBC180000000791GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnytop300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Top)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Black 3 Button Keypad (Skinny Middle)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-3button-bsb.png",
      id: "aBC180000000792GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnymiddle300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Middle)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Black 4 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-4button-sssb.png",
      id: "aBC180000000793GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bfatbottom300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Black 4 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-4button-bbud.png",
      id: "aBC180000000794GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b2fatarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad with Up/Down",
      buttonCount: 2,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Black 5 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-5button-bssud.png",
      id: "aBC180000000795GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfattoparrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Black 5 Button Split Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-5button-sbsud.png",
      id: "aBC180000000796GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfatmiddlearrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Split Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Black 5 Button Keypad Bottom with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-5button-ssbud.png",
      id: "aBC180000000797GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b1fat2skinnyarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad Bottom with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-BKLV06-00",
      productId: "01t0g00000ZFEQJAA5",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (BLACK)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Black 6 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-6button.png",
      id: "aBC180000000798GAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bSkinnywarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "6 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Fan",
      productSKU: "WIF-BKCONV-00",
      productId: "01t7000000K5OdcAAF",
      productDescription: "WIRELESS FAN CONTROL CONVERSION KIT BLACK",
      price: 7.5,
      name: "Metropolitan Fan Adaptive Black",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-fancontrol.png",
      id: "aBC18000000078IGAQ",
      finish: "Black",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/fancontrol.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Light Almond 6 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-6button.png",
      id: "aBC18000000078wGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bSkinnywarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "6 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-BKT102-00",
      productId: "01t0g00000ZFER7AAP",
      productDescription: "ECHO WIRELESS MLV DIMMER (BLACK)",
      price: 87.5,
      name: "Echo Paddle Forward/MLV Black",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC18000000079HGAQ",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-SWA102-00",
      productId: "01t0g00000ZFERHAA5",
      productDescription: "ECHO WIRELESS ADAPTIVE DIMMER (SNOW WHITE)",
      price: 87.5,
      name: "Echo Paddle Adaptive Snow White",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC18000000079WGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPB-LALV02-00",
      productId: "01t0g00000ZFEQdAAP",
      productDescription: "ECHO LOW VOLTAGE PADDLE KEYPAD (LIGHT ALMOND)",
      price: 87.5,
      name: "Echo Paddle Low Voltage Light Almond",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC18000000079XGAQ",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-LAS105-00",
      productId: "01t0g00000ZFEQ5AAP",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - SWITCH (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo 4 Button + Dial Switch Light Almond",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-dial-4button.png",
      id: "aBC1800000007AjGAI",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 3 Button Keypad (Skinny Middle)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-3button-bsb.png",
      id: "aBC18000000078XGAQ",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnymiddle300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Middle)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WIK-BKCONV-00",
      productId: "01t7000000K5OdhAAF",
      productDescription: "METROPOLITAN WIRELESS KEYPAD CONVERSION KIT BLACK",
      price: 16.0,
      name: "Metropolitan 4 Button + Dial Adaptive Black",
      msrp: 32.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-dial-4button.png",
      id: "aBC18000000077tGAA",
      finish: "Black",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WIK-SWS104-01",
      productId: "01t7000000TkIAwAAN",
      productDescription: "METROPOLITAN WIRELESS KEYPAD SNOW WHITE",
      price: 125.0,
      name: "Metropolitan 4 Button + Dial Adaptive Snow White",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-dial-4button.png",
      id: "aBC18000000077uGAA",
      finish: "Snow White",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 3 Button Keypad (Skinny Top)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-3button-sbb.png",
      id: "aBC180000000799GAA",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnytop300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Top)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 3 Button Keypad (Skinny Middle)",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-3button-bsb.png",
      id: "aBC18000000079AGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bskinnymiddle300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "3 Button Keypad (Skinny Middle)",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Snow White 4 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-4button-sssb.png",
      id: "aBC18000000079BGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bfatbottom300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 4 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-4button-bbud.png",
      id: "aBC18000000079CGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b2fatarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad with Up/Down",
      buttonCount: 2,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 5 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-5button-bssud.png",
      id: "aBC18000000079DGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfattoparrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 5 Button Split Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-5button-sbsud.png",
      id: "aBC18000000079EGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfatmiddlearrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Split Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Snow White 5 Button Keypad Bottom with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-5button-ssbud.png",
      id: "aBC18000000079FGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b1fat2skinnyarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad Bottom with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-SWLV06-00",
      productId: "01t0g00000ZEtauAAD",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (SNOW WHITE)",
      price: 125.0,
      name: "Echo Configurable Low Voltage Snow White 6 Button Keypad",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-6button.png",
      id: "aBC18000000079GGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4bSkinnywarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "6 Button Keypad",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPS-LAS102-00",
      productId: "01t0g00000ZFES0AAP",
      productDescription: "ECHO WIRELESS SWITCH (LIGHT ALMOND)",
      price: 70.0,
      name: "Echo Paddle Switch Light Almond",
      msrp: 140.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC18000000079bGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPB-SWLV02-00",
      productId: "01t0g00000ZFEQxAAP",
      productDescription: "ECHO LOW VOLTAGE PADDLE KEYPAD (SNOW WHITE)",
      price: 87.5,
      name: "Echo Paddle Low Voltage Snow White",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC18000000079RGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-SWT102-00",
      productId: "01t0g00000ZFERMAA5",
      productDescription: "ECHO WIRELESS MLV DIMMER (SNOW WHITE)",
      price: 87.5,
      name: "Echo Paddle Forward/MLV Snow White",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC18000000079SGAQ",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-LAA102-00",
      productId: "01t0g00000ZFER3AAP",
      productDescription: "ECHO WIRELESS ADAPTIVE DIMMER (LIGHT ALMOND)",
      price: 87.5,
      name: "Echo Paddle Adaptive Light Almond",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC18000000079vGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-LAA105-00",
      productId: "01t0g00000ZFERgAAP",
      productDescription:
        "ECHO WIRELESS DIAL KEYPAD - ADAPTIVE DIMMER (LIGHT ALMOND)",
      price: 125.0,
      name: "Echo 4 Button + Dial Adaptive Light Almond",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-dial-4button.png",
      id: "aBC1800000007AAGAY",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-SWLV05-00",
      productId: "01t0g00000ZEtaRAAT",
      productDescription: "ECHO LOW VOLTAGE DIAL KEYPAD (SNOW WHITE)",
      price: 125.0,
      name: "Echo 4 Button + Dial Low Voltage Snow White",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-dial-4button.png",
      id: "aBC1800000007ABGAY",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPS-BKS102-00",
      productId: "01t0g00000ZFERvAAP",
      productDescription: "ECHO WIRELESS SWITCH (BLACK)",
      price: 70.0,
      name: "Echo Paddle Switch Black",
      msrp: 140.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC18000000079MGAQ",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-BKA102-00",
      productId: "01t0g00000ZFER2AAP",
      productDescription: "ECHO WIRELESS ADAPTIVE DIMMER (BLACK)",
      price: 87.5,
      name: "Echo Paddle Adaptive Black",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC18000000079lGAA",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WID-LAS102-01",
      productId: "01t7000000TkIANAA3",
      productDescription: "METROPOLITAN WIRELESS DIMMER LIGHT ALMOND",
      price: 87.5,
      name: "Metropolitan Paddle Adaptive Light Almond",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC18000000077eGAA",
      finish: "Light Almond",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Fan",
      productSKU: "WIF-SWS104-00",
      productId: "01t7000000GbbycAAB",
      productDescription: "WIRELESS FAN CONTROLLER SNOW WHITE",
      price: 100.0,
      name: "Metropolitan Fan Adaptive Snow White",
      msrp: 200.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-fancontrol.png",
      id: "aBC18000000078DGAQ",
      finish: "Snow White",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/fancontrol.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WIS-SWS102-00",
      productId: "01t7000000Gbc4AAAR",
      productDescription: "METROPOLITAN WIRELESS SWITCH SNOW WHITE",
      price: 70.0,
      name: "Metropolitan Paddle Switch Snow White",
      msrp: 140.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC180000000783GAA",
      finish: "Snow White",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WID-SWS102-01",
      productId: "01t7000000TkIAXAA3",
      productDescription: "METROPOLITAN WIRELESS DIMMER SNOW WHITE",
      price: 87.5,
      name: "Metropolitan Paddle Adaptive Snow White",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC18000000077jGAA",
      finish: "Snow White",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-BKS105-00",
      productId: "01t0g00000ZFEPWAA5",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - SWITCH (BLACK)",
      price: 125.0,
      name: "Echo 4 Button + Dial Switch Black",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-dial-4button.png",
      id: "aBC1800000007AoGAI",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 5 Button Keypad Bottom with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-5button-ssbud.png",
      id: "aBC18000000078rGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b1fat2skinnyarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad Bottom with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WID-BKCONV-00",
      productId: "01t7000000K5OdXAAV",
      productDescription: "METROPOLITAN WIRELESS DIMMER CONVERSION KIT BLACK",
      price: 7.5,
      name: "Metropolitan Paddle Adaptive Black",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-paddlebutton.png",
      id: "aBC18000000077oGAA",
      finish: "Black",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Fan",
      productSKU: "WIF-LAS104-00",
      productId: "01t7000000Gbc1RAAR",
      productDescription: "WIRELESS FAN CONTROLLER LIGHT ALMOND",
      price: 100.0,
      name: "Metropolitan Fan Adaptive Light Almond",
      msrp: 200.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-fancontrol.png",
      id: "aBC18000000078NGAQ",
      finish: "Light Almond",
      family: "Metropolitan",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/fancontrol.png",
      controllerType: null,
      control: "Adaptive",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-BKT105-00",
      productId: "01t0g00000ZFERbAAP",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - MLV DIMMER (BLACK)",
      price: 125.0,
      name: "Echo 4 Button + Dial Forward/MLV Black",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BLK300-dial-4button.png",
      id: "aBC1800000007AUGAY",
      finish: "Black",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 5 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-5button-bssud.png",
      id: "aBC18000000078iGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfattoparrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 4 Button Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-4button-bbud.png",
      id: "aBC18000000078hGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/4b2fatarrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "4 Button Keypad with Up/Down",
      buttonCount: 2,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Configurable",
      productSKU: "WPB-LALV06-00",
      productId: "01t0g00000ZFEQiAAP",
      productDescription: "ECHO LOW VOLTAGE CONFIGURABLE KEYPAD (LIGHT ALMOND)",
      price: 125.0,
      name:
        "Echo Configurable Low Voltage Light Almond 5 Button Split Keypad with Up/Down",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-5button-sbsud.png",
      id: "aBC18000000078mGAA",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/3bfatmiddlearrows300.png",
      controllerType: null,
      control: "Low Voltage",
      configuration: null,
      buttonLayout: "5 Button Split Keypad with Up/Down",
      buttonCount: 3,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPS-SWS102-00",
      productId: "01t0g00000ZFES5AAP",
      productDescription: "ECHO WIRELESS SWITCH (SNOW WHITE)",
      price: 70.0,
      name: "Echo Paddle Switch Snow White",
      msrp: 140.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-paddlebutton.png",
      id: "aBC18000000079gGAA",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-SWT105-00",
      productId: "01t0g00000ZEzs6AAD",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - MLV DIMMER (SNOW WHITE)",
      price: 125.0,
      name: "Echo 4 Button + Dial Forward/MLV Snow White",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-dial-4button.png",
      id: "aBC1800000007AeGAI",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "4 Button + Dial",
      productSKU: "WPK-SWS105-00",
      productId: "01t0g00000ZEzs1AAD",
      productDescription: "ECHO WIRELESS DIAL KEYPAD - SWITCH (SNOW WHITE)",
      price: 125.0,
      name: "Echo 4 Button + Dial Switch Snow White",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH300-dial-4button.png",
      id: "aBC1800000007AfGAI",
      finish: "Snow White",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/MetropolitanEngravingPDFImage.png",
      controllerType: null,
      control: "Switch",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 4,
      amperage: null,
      active: true
    },
    {
      type: "Keypad",
      style: "Paddle",
      productSKU: "WPD-LAT102-00",
      productId: "01t0g00000ZFERCAA5",
      productDescription: "ECHO WIRELESS MLV DIMMER (LIGHT ALMOND)",
      price: 87.5,
      name: "Echo Paddle Forward/MLV Light Almond",
      msrp: 175.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL300-paddlebutton.png",
      id: "aBC1800000007A0GAI",
      finish: "Light Almond",
      family: "Echo",
      equipmentType: null,
      diagram:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Lines/metro-paddle.png",
      controllerType: null,
      control: "Forward/MLV",
      configuration: null,
      buttonLayout: "Non-Configurable",
      buttonCount: 0,
      amperage: null,
      active: true
    }
  ],
  faceplates: [
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI2-0S0LAP-00",
      productId: "01t7000000Gbc2JAAR",
      productDescription: "SCREWLESS FACEPLATE: TWO GANG (LIGHT ALMOND)",
      price: 5.0,
      name: "2 Gang Light Almond",
      msrp: 10.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL-2gang-300.png",
      id: "aBC180000000770GAA",
      finish: "Light Almond",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "2 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI1-0S0SWP-01",
      productId: "01t0g00000ZFZ4rAAH",
      productDescription: "SCREWLESS FACEPLATE: SINGLE GANG (SNOW WHITE)",
      price: 4.0,
      name: "1 Gang Snow White",
      msrp: 8.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH-solo-300.png",
      id: "aBC18000000076lGAA",
      finish: "Snow White",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "1 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI2-0S0BKP-00",
      productId: "01t7000000K5OdDAAV",
      productDescription: "SCREWLESS FACEPLATE: TWO GANG (BLACK)",
      price: 5.0,
      name: "2 Gang Black",
      msrp: 10.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BL-2gang-300.png",
      id: "aBC18000000076vGAA",
      finish: "Black",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "2 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI3-0S0SWP-00",
      productId: "01t7000000Gbc2YAAR",
      productDescription: "SCREWLESS FACEPLATE: THREE GANG (SNOW WHITE)",
      price: 7.5,
      name: "3 Gang Snow White",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH-3gang-300.png",
      id: "aBC18000000077FGAQ",
      finish: "Snow White",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "3 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI3-0S0LAP-00",
      productId: "01t7000000Gbc2TAAR",
      productDescription: "SCREWLESS FACEPLATE: THREE GANG (LIGHT ALMOND)",
      price: 7.5,
      name: "3 Gang Light Almond",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL-3gang-300.png",
      id: "aBC18000000077KGAQ",
      finish: "Light Almond",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "3 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI4-0S0SWP-00",
      productId: "01t7000000Gbc2iAAB",
      productDescription: "SCREWLESS FACEPLATE: FOUR GANG (SNOW WHITE)",
      price: 10.0,
      name: "4 Gang Snow White",
      msrp: 20.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH-4gang-300.png",
      id: "aBC18000000077PGAQ",
      finish: "Snow White",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "4 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI4-0S0BKP-00",
      productId: "01t7000000K5OdNAAV",
      productDescription: "SCREWLESS FACEPLATE: FOUR GANG (BLACK)",
      price: 10.0,
      name: "4 Gang Black",
      msrp: 20.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BL-4gang-300.png",
      id: "aBC18000000077UGAQ",
      finish: "Black",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "4 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI2-0S0SWP-00",
      productId: "01t7000000Gbc2OAAR",
      productDescription: "SCREWLESS FACEPLATE: TWO GANG (SNOW WHITE)",
      price: 5.0,
      name: "2 Gang Snow White",
      msrp: 10.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/WH-2gang-300.png",
      id: "aBC180000000775GAA",
      finish: "Snow White",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "2 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI1-0S0BKP-01",
      productId: "01t0g00000ZFZ4hAAH",
      productDescription: "SCREWLESS FACEPLATE: SINGLE GANG (BLACK)",
      price: null,
      name: "1 Gang Black",
      msrp: 0.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BL-solo-300.png",
      id: "aBC18000000076gGAA",
      finish: "Black",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "1 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI1-0S0LAP-01",
      productId: "01t0g00000ZFZ4mAAH",
      productDescription: "SCREWLESS FACEPLATE: SINGLE GANG (LIGHT ALMOND)",
      price: null,
      name: "1 Gang Light Almond",
      msrp: 0.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL-solo-300.png",
      id: "aBC18000000076qGAA",
      finish: "Light Almond",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "1 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI4-0S0LAP-00",
      productId: "01t7000000Gbc2dAAB",
      productDescription: "SCREWLESS FACEPLATE: FOUR GANG (LIGHT ALMOND)",
      price: 10.0,
      name: "4 Gang Light Almond",
      msrp: 20.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/AL-4gang-300.png",
      id: "aBC18000000077ZGAQ",
      finish: "Light Almond",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "4 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Faceplate",
      style: null,
      productSKU: "FI3-0S0BKP-00",
      productId: "01t7000000K5OdIAAV",
      productDescription: "SCREWLESS FACEPLATE: THREE GANG (BLACK)",
      price: 7.5,
      name: "3 Gang Black",
      msrp: 15.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/KeyPadTool/KeypadFiles/Assets/BL-3gang-300.png",
      id: "aBC18000000077AGAQ",
      finish: "Black",
      family: null,
      equipmentType: null,
      diagram: null,
      controllerType: null,
      control: null,
      configuration: "3 Gang",
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    }
  ],
  equipment: [
    {
      type: "Equipment",
      style: null,
      productSKU: "LCB-010V8-01",
      productId: "01t0g00000ZG2O6AAL",
      productDescription: "WIRED 0-10V CONTROL 8 CHANNELS",
      price: 325.0,
      name: "Wired 0-10v Control 8 Channels",
      msrp: 650.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/0-10%20Controller%20Thumb.png",
      id: "aBC1800000007QrGAI",
      finish: null,
      family: null,
      equipmentType: "Lighting",
      diagram: null,
      controllerType: "Loads",
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "LCB-DMX1-01",
      productId: "01t0g00000ZG2OGAA1",
      productDescription: "WIRED DMX LOW VOLTAGE LIGHTING CONTROLLER",
      price: 325.0,
      name: "Wired DMX Low Voltage Lighting Controller",
      msrp: 650.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/DMX%20ControllerThumb.png",
      id: "aBC1800000007QmGAI",
      finish: null,
      family: null,
      equipmentType: "Lighting",
      diagram: null,
      controllerType: "Loads",
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SHA-FBINDCHOICE-00",
      productId: "01t0g00000VFlWyAAL",
      productDescription: "SAVANT CHOICE FABRIC AND BRACKET BINDER",
      price: null,
      name: "Savant Choice Fabric and Bracket Binder",
      msrp: 350.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/EcomJS/200SHA-FBINDCHOICE_1.png",
      id: "aBC1800000007CuGAI",
      finish: null,
      family: null,
      equipmentType: "Shades",
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SKL-3040-00",
      productId: "01t0g00000blXLyAAM",
      productDescription: "40 KEYPAD POWER AND CONTROL MODULE",
      price: 300.0,
      name: "40 Keypad Power and Control Module",
      msrp: 600.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: 40,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/SKL-3040-front-thumb.png",
      id: "aBC1800000007DJGAY",
      finish: null,
      family: null,
      equipmentType: "Lighting",
      diagram: null,
      controllerType: "Keypads",
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SHA-W1000-00",
      productId: "01t7000000RanFmAAJ",
      productDescription: "SHADE OR LOW VOLTAGE KEYPAD WIRE 1000FT SPOOL",
      price: 510.0,
      name: "Shade or Low Voltage Keypad Wire 1000ft Spool",
      msrp: 850.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/SHA-W1000-1_thumb.png",
      id: "aBC1800000007D9GAI",
      finish: null,
      family: null,
      equipmentType: "Accessories",
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SKL-1010-00",
      productId: "01t0g00000blXC3AAM",
      productDescription: "10 KEYPAD POWER AND CONTROLLER",
      price: 125.0,
      name: "10 Keypad Power and Controller",
      msrp: 250.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: 10,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/keypad-link-front-1010-thumb.png",
      id: "aBC1800000007DEGAY",
      finish: null,
      family: null,
      equipmentType: "Lighting",
      diagram: null,
      controllerType: "Keypads",
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SHA-FBINDMERMET-00",
      productId: "01t0g00000VFlX3AAL",
      productDescription:
        "MERMET BINDERS FOR SAMPLES OF ALL MERMET FABRIC SAVANT IS OFFERING",
      price: null,
      name: "Mermet Fabric Binders",
      msrp: 150.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image:
        "https://sweb-img.s3.amazonaws.com/ecom_Images/SHA-FBINDMERMET_small.png",
      id: "aBC1800000007D4GAI",
      finish: null,
      family: null,
      equipmentType: "Shades",
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    },
    {
      type: "Equipment",
      style: null,
      productSKU: "SHA-FBINDVERTILUX-00",
      productId: "01t0g00000VFlX8AAL",
      productDescription:
        "VERTILUX BINDERS FOR SAMPLES OF ALL VERTILUX FABRIC SAVANT IS OFFERING",
      price: null,
      name: "Vertilux Fabric Binders",
      msrp: 150.0,
      moduleType: null,
      maxVoltage: null,
      maxConnections: null,
      image: "http://sweb-img.s3.amazonaws.com/ecom_Images/rmp6wrd3.jpg",
      id: "aBC1800000007CzGAI",
      finish: null,
      family: null,
      equipmentType: "Shades",
      diagram: null,
      controllerType: null,
      control: null,
      configuration: null,
      buttonLayout: null,
      buttonCount: null,
      amperage: null,
      active: true
    }
  ]
};
